CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "user" (
  "id" UUID DEFAULT gen_random_uuid() UNIQUE PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT DEFAULT 'n/a 2',
  "age" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  "active" BOOLEAN DEFAULT true
);

CREATE TABLE "post" (
  "id" UUID DEFAULT gen_random_uuid() UNIQUE PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "author" UUID NOT NULL,
  FOREIGN KEY ("author") REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE TABLE "post_likes" (
  "post" UUID NOT NULL,
  "user" UUID NOT NULL,
  PRIMARY KEY ("post", "user"),
  FOREIGN KEY ("post") REFERENCES "post"(id) ON DELETE CASCADE,
  FOREIGN KEY ("user") REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE "comment" (
  "id" UUID DEFAULT gen_random_uuid() UNIQUE PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "post" UUID NOT NULL,
  "content" TEXT NOT NULL,
  "author" TEXT NOT NULL,
  FOREIGN KEY ("post") REFERENCES "post"("id") ON DELETE CASCADE,
  FOREIGN KEY ("author") REFERENCES "user"("email") ON DELETE CASCADE
);