/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_abstract = 3,
  anon_sym_model = 4,
  anon_sym_extends = 5,
  anon_sym_COMMA = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_COLON = 9,
  anon_sym_SEMI = 10,
  anon_sym_required = 11,
  anon_sym_optional = 12,
  anon_sym_multi = 13,
  anon_sym_single = 14,
  anon_sym_default = 15,
  anon_sym_constraint = 16,
  anon_sym_on = 17,
  anon_sym_AT = 18,
  anon_sym_before = 19,
  anon_sym_after = 20,
  anon_sym_COLON_EQ = 21,
  anon_sym_str = 22,
  anon_sym_int16 = 23,
  anon_sym_int32 = 24,
  anon_sym_int64 = 25,
  anon_sym_float32 = 26,
  anon_sym_float64 = 27,
  anon_sym_bool = 28,
  anon_sym_uuid = 29,
  anon_sym_datetime = 30,
  anon_sym_json = 31,
  anon_sym_bytes = 32,
  anon_sym_DOT = 33,
  anon_sym_ATfunc = 34,
  anon_sym_LPAREN = 35,
  anon_sym_RPAREN = 36,
  sym_string_literal = 37,
  sym_number_literal = 38,
  anon_sym_true = 39,
  anon_sym_false = 40,
  sym_source_file = 41,
  sym__definition = 42,
  sym_abstract_model = 43,
  sym_model = 44,
  sym_extends_clause = 45,
  sym_model_body = 46,
  sym__model_member = 47,
  sym_field_declaration = 48,
  sym_cardinality = 49,
  sym_field_body = 50,
  sym__field_attribute = 51,
  sym_default_clause = 52,
  sym_constraint = 53,
  sym_on_clause = 54,
  sym_trigger = 55,
  sym_trigger_body = 56,
  sym_assignment = 57,
  sym_type_expr = 58,
  sym_builtin_type = 59,
  sym_expression = 60,
  sym_member_expression = 61,
  sym_function_call = 62,
  sym_argument_list = 63,
  sym_boolean_literal = 64,
  aux_sym_source_file_repeat1 = 65,
  aux_sym_extends_clause_repeat1 = 66,
  aux_sym_model_body_repeat1 = 67,
  aux_sym_field_body_repeat1 = 68,
  aux_sym_trigger_body_repeat1 = 69,
  aux_sym_argument_list_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_abstract] = "abstract",
  [anon_sym_model] = "model",
  [anon_sym_extends] = "extends",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_required] = "required",
  [anon_sym_optional] = "optional",
  [anon_sym_multi] = "multi",
  [anon_sym_single] = "single",
  [anon_sym_default] = "default",
  [anon_sym_constraint] = "constraint",
  [anon_sym_on] = "on",
  [anon_sym_AT] = "@",
  [anon_sym_before] = "before",
  [anon_sym_after] = "after",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_str] = "str",
  [anon_sym_int16] = "int16",
  [anon_sym_int32] = "int32",
  [anon_sym_int64] = "int64",
  [anon_sym_float32] = "float32",
  [anon_sym_float64] = "float64",
  [anon_sym_bool] = "bool",
  [anon_sym_uuid] = "uuid",
  [anon_sym_datetime] = "datetime",
  [anon_sym_json] = "json",
  [anon_sym_bytes] = "bytes",
  [anon_sym_DOT] = ".",
  [anon_sym_ATfunc] = "@func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_string_literal] = "string_literal",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_abstract_model] = "abstract_model",
  [sym_model] = "model",
  [sym_extends_clause] = "extends_clause",
  [sym_model_body] = "model_body",
  [sym__model_member] = "_model_member",
  [sym_field_declaration] = "field_declaration",
  [sym_cardinality] = "cardinality",
  [sym_field_body] = "field_body",
  [sym__field_attribute] = "_field_attribute",
  [sym_default_clause] = "default_clause",
  [sym_constraint] = "constraint",
  [sym_on_clause] = "on_clause",
  [sym_trigger] = "trigger",
  [sym_trigger_body] = "trigger_body",
  [sym_assignment] = "assignment",
  [sym_type_expr] = "type_expr",
  [sym_builtin_type] = "builtin_type",
  [sym_expression] = "expression",
  [sym_member_expression] = "member_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_extends_clause_repeat1] = "extends_clause_repeat1",
  [aux_sym_model_body_repeat1] = "model_body_repeat1",
  [aux_sym_field_body_repeat1] = "field_body_repeat1",
  [aux_sym_trigger_body_repeat1] = "trigger_body_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_required] = anon_sym_required,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_multi] = anon_sym_multi,
  [anon_sym_single] = anon_sym_single,
  [anon_sym_default] = anon_sym_default,
  [anon_sym_constraint] = anon_sym_constraint,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_before] = anon_sym_before,
  [anon_sym_after] = anon_sym_after,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_int16] = anon_sym_int16,
  [anon_sym_int32] = anon_sym_int32,
  [anon_sym_int64] = anon_sym_int64,
  [anon_sym_float32] = anon_sym_float32,
  [anon_sym_float64] = anon_sym_float64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_uuid] = anon_sym_uuid,
  [anon_sym_datetime] = anon_sym_datetime,
  [anon_sym_json] = anon_sym_json,
  [anon_sym_bytes] = anon_sym_bytes,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATfunc] = anon_sym_ATfunc,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_string_literal] = sym_string_literal,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_abstract_model] = sym_abstract_model,
  [sym_model] = sym_model,
  [sym_extends_clause] = sym_extends_clause,
  [sym_model_body] = sym_model_body,
  [sym__model_member] = sym__model_member,
  [sym_field_declaration] = sym_field_declaration,
  [sym_cardinality] = sym_cardinality,
  [sym_field_body] = sym_field_body,
  [sym__field_attribute] = sym__field_attribute,
  [sym_default_clause] = sym_default_clause,
  [sym_constraint] = sym_constraint,
  [sym_on_clause] = sym_on_clause,
  [sym_trigger] = sym_trigger,
  [sym_trigger_body] = sym_trigger_body,
  [sym_assignment] = sym_assignment,
  [sym_type_expr] = sym_type_expr,
  [sym_builtin_type] = sym_builtin_type,
  [sym_expression] = sym_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_extends_clause_repeat1] = aux_sym_extends_clause_repeat1,
  [aux_sym_model_body_repeat1] = aux_sym_model_body_repeat1,
  [aux_sym_field_body_repeat1] = aux_sym_field_body_repeat1,
  [aux_sym_trigger_body_repeat1] = aux_sym_trigger_body_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_multi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_single] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_default] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constraint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_before] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_after] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uuid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_json] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bytes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfunc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_abstract_model] = {
    .visible = true,
    .named = true,
  },
  [sym_model] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_model_body] = {
    .visible = true,
    .named = true,
  },
  [sym__model_member] = {
    .visible = false,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_cardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_field_body] = {
    .visible = true,
    .named = true,
  },
  [sym__field_attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_default_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_on_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_body] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_type_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extends_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_model_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trigger_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_event = 2,
  field_name = 3,
  field_object = 4,
  field_property = 5,
  field_timing = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_event] = "event",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_timing] = "timing",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 2},
  [9] = {.index = 16, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 1},
  [2] =
    {field_body, 3},
    {field_name, 2},
  [4] =
    {field_body, 3},
    {field_name, 1},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_name, 1},
    {field_type, 3},
  [10] =
    {field_event, 2},
    {field_name, 3},
    {field_timing, 1},
  [13] =
    {field_name, 1},
  [14] =
    {field_object, 0},
    {field_property, 2},
  [16] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        '#', 16,
        '\'', 4,
        '(', 28,
        ')', 29,
        ',', 17,
        '-', 11,
        '.', 26,
        '/', 5,
        ':', 21,
        ';', 22,
        '@', 24,
        '{', 18,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 16,
        '\'', 4,
        ')', 29,
        ',', 17,
        '-', 11,
        '.', 26,
        '/', 5,
        ':', 6,
        ';', 22,
        '@', 8,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ATfunc);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'j', 8,
        'm', 9,
        'o', 10,
        'r', 11,
        's', 12,
        't', 13,
        'u', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'x') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(30);
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'q') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 47:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 48:
      if (lookahead == '1') ADVANCE(69);
      if (lookahead == '3') ADVANCE(70);
      if (lookahead == '6') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(76);
      END_STATE();
    case 54:
      if (lookahead == 'g') ADVANCE(77);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(83);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(86);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(87);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 69:
      if (lookahead == '6') ADVANCE(90);
      END_STATE();
    case 70:
      if (lookahead == '2') ADVANCE(91);
      END_STATE();
    case 71:
      if (lookahead == '4') ADVANCE(92);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_json);
      END_STATE();
    case 73:
      if (lookahead == 'l') ADVANCE(93);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(94);
      END_STATE();
    case 75:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 77:
      if (lookahead == 'l') ADVANCE(97);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_uuid);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_after);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_bytes);
      END_STATE();
    case 84:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 85:
      if (lookahead == 'i') ADVANCE(101);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(102);
      END_STATE();
    case 87:
      if (lookahead == 'd') ADVANCE(103);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 89:
      if (lookahead == '3') ADVANCE(104);
      if (lookahead == '6') ADVANCE(105);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_int16);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_int32);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_int64);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_multi);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 98:
      if (lookahead == 'c') ADVANCE(109);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_before);
      END_STATE();
    case 100:
      if (lookahead == 'a') ADVANCE(110);
      END_STATE();
    case 101:
      if (lookahead == 'm') ADVANCE(111);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 103:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 104:
      if (lookahead == '2') ADVANCE(114);
      END_STATE();
    case 105:
      if (lookahead == '4') ADVANCE(115);
      END_STATE();
    case 106:
      if (lookahead == 'a') ADVANCE(116);
      END_STATE();
    case 107:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_single);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 110:
      if (lookahead == 'i') ADVANCE(119);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_default);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_float32);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_float64);
      END_STATE();
    case 116:
      if (lookahead == 'l') ADVANCE(121);
      END_STATE();
    case 117:
      if (lookahead == 'd') ADVANCE(122);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 119:
      if (lookahead == 'n') ADVANCE(123);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_required);
      END_STATE();
    case 123:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_constraint);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_required] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_multi] = ACTIONS(1),
    [anon_sym_single] = ACTIONS(1),
    [anon_sym_default] = ACTIONS(1),
    [anon_sym_constraint] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_before] = ACTIONS(1),
    [anon_sym_after] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_int16] = ACTIONS(1),
    [anon_sym_int32] = ACTIONS(1),
    [anon_sym_int64] = ACTIONS(1),
    [anon_sym_float32] = ACTIONS(1),
    [anon_sym_float64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_uuid] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [anon_sym_json] = ACTIONS(1),
    [anon_sym_bytes] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ATfunc] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(81),
    [sym__definition] = STATE(21),
    [sym_abstract_model] = STATE(21),
    [sym_model] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_abstract] = ACTIONS(9),
    [anon_sym_model] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(40), 1,
      sym_type_expr,
    STATE(53), 1,
      sym_builtin_type,
    ACTIONS(15), 11,
      anon_sym_str,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_float32,
      anon_sym_float64,
      anon_sym_bool,
      anon_sym_uuid,
      anon_sym_datetime,
      anon_sym_json,
      anon_sym_bytes,
  [26] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(41), 1,
      sym_type_expr,
    STATE(53), 1,
      sym_builtin_type,
    ACTIONS(15), 11,
      anon_sym_str,
      anon_sym_int16,
      anon_sym_int32,
      anon_sym_int64,
      anon_sym_float32,
      anon_sym_float64,
      anon_sym_bool,
      anon_sym_uuid,
      anon_sym_datetime,
      anon_sym_json,
      anon_sym_bytes,
  [52] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    STATE(58), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_assignment,
      aux_sym_trigger_body_repeat1,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [85] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    ACTIONS(32), 1,
      anon_sym_ATfunc,
    STATE(58), 1,
      sym_expression,
    ACTIONS(35), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(38), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_assignment,
      aux_sym_trigger_body_repeat1,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [118] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_assignment,
      aux_sym_trigger_body_repeat1,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [151] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_required,
    ACTIONS(51), 1,
      anon_sym_optional,
    ACTIONS(57), 1,
      anon_sym_AT,
    STATE(69), 1,
      sym_cardinality,
    ACTIONS(54), 2,
      anon_sym_multi,
      anon_sym_single,
    STATE(7), 4,
      sym__model_member,
      sym_field_declaration,
      sym_trigger,
      aux_sym_model_body_repeat1,
  [183] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_required,
    ACTIONS(66), 1,
      anon_sym_optional,
    ACTIONS(70), 1,
      anon_sym_AT,
    STATE(69), 1,
      sym_cardinality,
    ACTIONS(68), 2,
      anon_sym_multi,
      anon_sym_single,
    STATE(7), 4,
      sym__model_member,
      sym_field_declaration,
      sym_trigger,
      aux_sym_model_body_repeat1,
  [215] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_required,
    ACTIONS(66), 1,
      anon_sym_optional,
    ACTIONS(70), 1,
      anon_sym_AT,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_cardinality,
    ACTIONS(68), 2,
      anon_sym_multi,
      anon_sym_single,
    STATE(8), 4,
      sym__model_member,
      sym_field_declaration,
      sym_trigger,
      aux_sym_model_body_repeat1,
  [247] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [276] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [305] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [334] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    STATE(60), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [360] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    STATE(59), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [386] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_ATfunc,
    STATE(49), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string_literal,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 3,
      sym_member_expression,
      sym_function_call,
      sym_boolean_literal,
  [412] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      anon_sym_default,
    ACTIONS(84), 1,
      anon_sym_constraint,
    ACTIONS(86), 1,
      anon_sym_on,
    STATE(17), 5,
      sym__field_attribute,
      sym_default_clause,
      sym_constraint,
      sym_on_clause,
      aux_sym_field_body_repeat1,
  [435] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_default,
    ACTIONS(84), 1,
      anon_sym_constraint,
    ACTIONS(86), 1,
      anon_sym_on,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(18), 5,
      sym__field_attribute,
      sym_default_clause,
      sym_constraint,
      sym_on_clause,
      aux_sym_field_body_repeat1,
  [458] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    ACTIONS(92), 1,
      anon_sym_default,
    ACTIONS(95), 1,
      anon_sym_constraint,
    ACTIONS(98), 1,
      anon_sym_on,
    STATE(18), 5,
      sym__field_attribute,
      sym_default_clause,
      sym_constraint,
      sym_on_clause,
      aux_sym_field_body_repeat1,
  [481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_RBRACE,
      anon_sym_AT,
    ACTIONS(101), 5,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_multi,
      anon_sym_single,
      sym_identifier,
  [496] = 5,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_abstract,
    ACTIONS(113), 1,
      anon_sym_model,
    STATE(20), 4,
      sym__definition,
      sym_abstract_model,
      sym_model,
      aux_sym_source_file_repeat1,
  [515] = 5,
    ACTIONS(9), 1,
      anon_sym_abstract,
    ACTIONS(11), 1,
      anon_sym_model,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      sym_comment,
    STATE(20), 4,
      sym__definition,
      sym_abstract_model,
      sym_model,
      aux_sym_source_file_repeat1,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_RBRACE,
      anon_sym_AT,
    ACTIONS(120), 5,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_multi,
      anon_sym_single,
      sym_identifier,
  [549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_RBRACE,
      anon_sym_AT,
    ACTIONS(124), 5,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_multi,
      anon_sym_single,
      sym_identifier,
  [564] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_RBRACE,
      anon_sym_AT,
    ACTIONS(128), 5,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_multi,
      anon_sym_single,
      sym_identifier,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_RBRACE,
      anon_sym_AT,
    ACTIONS(132), 5,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_multi,
      anon_sym_single,
      sym_identifier,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(138), 4,
      anon_sym_RBRACE,
      anon_sym_ATfunc,
      sym_string_literal,
      sym_number_literal,
  [609] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 5,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 5,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 5,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_COLON_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 4,
      anon_sym_RBRACE,
      anon_sym_default,
      anon_sym_constraint,
      anon_sym_on,
  [663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 4,
      anon_sym_RBRACE,
      anon_sym_default,
      anon_sym_constraint,
      anon_sym_on,
  [673] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_argument_list_repeat1,
  [689] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_extends,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_model_body,
    STATE(55), 1,
      sym_extends_clause,
  [705] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 4,
      anon_sym_RBRACE,
      anon_sym_default,
      anon_sym_constraint,
      anon_sym_on,
  [715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 4,
      anon_sym_RBRACE,
      anon_sym_default,
      anon_sym_constraint,
      anon_sym_on,
  [725] = 1,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_abstract,
      anon_sym_model,
  [732] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      aux_sym_extends_clause_repeat1,
  [745] = 1,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_abstract,
      anon_sym_model,
  [752] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      anon_sym_SEMI,
    STATE(75), 1,
      sym_field_body,
  [765] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    STATE(73), 1,
      sym_field_body,
  [778] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      aux_sym_extends_clause_repeat1,
  [791] = 1,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_abstract,
      anon_sym_model,
  [798] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 2,
      anon_sym_multi,
      anon_sym_single,
  [809] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_argument_list_repeat1,
  [822] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      aux_sym_extends_clause_repeat1,
  [835] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_SEMI,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      sym_argument_list,
  [848] = 1,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_abstract,
      anon_sym_model,
  [855] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_argument_list_repeat1,
  [879] = 1,
    ACTIONS(206), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_abstract,
      anon_sym_model,
  [886] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_model_body,
  [896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [912] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_model_body,
  [922] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    STATE(82), 1,
      sym_trigger_body,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [940] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(214), 1,
      anon_sym_COLON_EQ,
  [950] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [960] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(218), 1,
      anon_sym_SEMI,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      anon_sym_before,
      anon_sym_after,
  [978] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_required,
  [988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_SEMI,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_SEMI,
  [1002] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_SEMI,
  [1009] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_identifier,
  [1016] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_COLON,
  [1023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_identifier,
  [1030] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identifier,
  [1037] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_identifier,
  [1044] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_SEMI,
  [1051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_model,
  [1058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_SEMI,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      sym_identifier,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_SEMI,
  [1079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_SEMI,
  [1086] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_identifier,
  [1093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [1100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_SEMI,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LPAREN,
  [1114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_SEMI,
  [1128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_SEMI,
  [1135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
  [1142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_identifier,
  [1149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_identifier,
  [1156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SEMI,
  [1163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_identifier,
  [1170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_SEMI,
  [1177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_identifier,
  [1184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_identifier,
  [1198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_SEMI,
  [1205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 85,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 247,
  [SMALL_STATE(11)] = 276,
  [SMALL_STATE(12)] = 305,
  [SMALL_STATE(13)] = 334,
  [SMALL_STATE(14)] = 360,
  [SMALL_STATE(15)] = 386,
  [SMALL_STATE(16)] = 412,
  [SMALL_STATE(17)] = 435,
  [SMALL_STATE(18)] = 458,
  [SMALL_STATE(19)] = 481,
  [SMALL_STATE(20)] = 496,
  [SMALL_STATE(21)] = 515,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 549,
  [SMALL_STATE(24)] = 564,
  [SMALL_STATE(25)] = 579,
  [SMALL_STATE(26)] = 594,
  [SMALL_STATE(27)] = 609,
  [SMALL_STATE(28)] = 620,
  [SMALL_STATE(29)] = 631,
  [SMALL_STATE(30)] = 642,
  [SMALL_STATE(31)] = 653,
  [SMALL_STATE(32)] = 663,
  [SMALL_STATE(33)] = 673,
  [SMALL_STATE(34)] = 689,
  [SMALL_STATE(35)] = 705,
  [SMALL_STATE(36)] = 715,
  [SMALL_STATE(37)] = 725,
  [SMALL_STATE(38)] = 732,
  [SMALL_STATE(39)] = 745,
  [SMALL_STATE(40)] = 752,
  [SMALL_STATE(41)] = 765,
  [SMALL_STATE(42)] = 778,
  [SMALL_STATE(43)] = 791,
  [SMALL_STATE(44)] = 798,
  [SMALL_STATE(45)] = 809,
  [SMALL_STATE(46)] = 822,
  [SMALL_STATE(47)] = 835,
  [SMALL_STATE(48)] = 848,
  [SMALL_STATE(49)] = 855,
  [SMALL_STATE(50)] = 866,
  [SMALL_STATE(51)] = 879,
  [SMALL_STATE(52)] = 886,
  [SMALL_STATE(53)] = 896,
  [SMALL_STATE(54)] = 904,
  [SMALL_STATE(55)] = 912,
  [SMALL_STATE(56)] = 922,
  [SMALL_STATE(57)] = 932,
  [SMALL_STATE(58)] = 940,
  [SMALL_STATE(59)] = 950,
  [SMALL_STATE(60)] = 960,
  [SMALL_STATE(61)] = 970,
  [SMALL_STATE(62)] = 978,
  [SMALL_STATE(63)] = 988,
  [SMALL_STATE(64)] = 995,
  [SMALL_STATE(65)] = 1002,
  [SMALL_STATE(66)] = 1009,
  [SMALL_STATE(67)] = 1016,
  [SMALL_STATE(68)] = 1023,
  [SMALL_STATE(69)] = 1030,
  [SMALL_STATE(70)] = 1037,
  [SMALL_STATE(71)] = 1044,
  [SMALL_STATE(72)] = 1051,
  [SMALL_STATE(73)] = 1058,
  [SMALL_STATE(74)] = 1065,
  [SMALL_STATE(75)] = 1072,
  [SMALL_STATE(76)] = 1079,
  [SMALL_STATE(77)] = 1086,
  [SMALL_STATE(78)] = 1093,
  [SMALL_STATE(79)] = 1100,
  [SMALL_STATE(80)] = 1107,
  [SMALL_STATE(81)] = 1114,
  [SMALL_STATE(82)] = 1121,
  [SMALL_STATE(83)] = 1128,
  [SMALL_STATE(84)] = 1135,
  [SMALL_STATE(85)] = 1142,
  [SMALL_STATE(86)] = 1149,
  [SMALL_STATE(87)] = 1156,
  [SMALL_STATE(88)] = 1163,
  [SMALL_STATE(89)] = 1170,
  [SMALL_STATE(90)] = 1177,
  [SMALL_STATE(91)] = 1184,
  [SMALL_STATE(92)] = 1191,
  [SMALL_STATE(93)] = 1198,
  [SMALL_STATE(94)] = 1205,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_trigger_body_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trigger_body_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trigger_body_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trigger_body_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_trigger_body_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_body_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_body_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 4, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 4, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 5, 0, 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5, 0, 4),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 5, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 6, 0, 6),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 6, 0, 6),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 6, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 6, 0, 5),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 8),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 9),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_clause, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_clause, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 4, 0, 7),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 3, 0, 7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model, 3, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_clause, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_abstract_model, 4, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cardinality, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_clause, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model, 4, 0, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_expr, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_body, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_body, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_body, 2, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_body, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cardinality, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cardinality, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_axel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "axel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
